### ISSUE TITLE
文章中的代码问题

### ISSUE THREAD

**Issue by shui00cc** [jieyugit/jieyugit.github.io#1]
在golang-channel这篇文章中，“双向管道”和“单向管道”两个板块的代码均存在问题。
1. “双向管道”代码中两个goroutine函数中`if ok == nil`，ok是bool type，用于检查channel是否关闭，则此处应修改为`if ok == true`
2. “单向管道”代码中由于没有关闭通道，goroutine 在接收完数据后可能会阻塞，导致deadlock。可以在main函数中发送完数据后`close(ch)`或其他方式解决
3. 两段代码实际上都是在main函数中使用双向通道，goroutine函数中使用send-only单向通道。

**Comment by jieyugit** [comment]
感谢指正~ 代码不够严谨 已重新上传示例代码
